services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
    environment:
      NODE_ENV: development
    command: make dev
    depends_on:
      db:
        condition: service_healthy

  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"   # HTTP
      - "443:443" # HTTPS
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app
    restart: unless-stopped

  db:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

volumes:
  caddy_data:
  caddy_config: